parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      maxParallel: 4
      matrix:
        node-14:
          node_version: ^14.15.0
        node-12:
          node_version: ^12.2.0
        node-10:
          node_version: ^10.10.0
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run build
        displayName: NPM run build
      - script: npm run test
        displayName: 'NPM run test'
