jobs:
  - job: npm
    steps:
      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'
      - script: |
          npm publish --dry-run
        displayName: 'npm publish --dry-run'
      - task: Npm@1
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
        inputs:
          command: publish
          publishEndpoint: 'npm-connection'
        displayName: 'Publish to NPM'
