trigger:
  branches:
    include:
      - refs/heads/*
    exclude:
      - refs/tags/*

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '^10.10.0'
        displayName: 'Install Node.js'
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run build
        displayName: 'NPM run build'

  - job: Lint
    dependsOn: Build
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '^10.10.0'
        displayName: 'Install Node.js'
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run lint-ci
        displayName: 'Run lint'

  - job: Test
    dependsOn:
      - Build
      - Lint
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '^10.10.0'
        displayName: 'Install Node.js'
      - script: npm install
        displayName: 'Install dependencies'
      - script: npm run test
        displayName: 'NPM run test'
      - script: npm install codecov --save-dev
        displayName: 'Installing codecov'
      - script: npm run test-coverage
        displayName: 'Run tests with coverage'
      - script: |
          ./node_modules/.bin/codecov --token=$(CODECOV_TOKEN)
        displayName: 'Upload coverage to codecov.io'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
        displayName: 'Publish code coverage results'
