name: Publish

on:
  release:
    types: [published]
  repository_dispatch:
    types: [publish]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install npm CLI
        run: |
          npm install -g npm@latest
          npm -v

      - name: Install dependencies and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Publish Dry Run
        run: npm publish --dry-run

      - name: Publish the package
        run: npm stage publish --provenance
